version: "3.8"
services:
  api_service:
    build:
      context: .
      dockerfile: Dockerfile-local
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo:latest"
    restart: always
    ports:
      - 27017:27017